### PR TITLE
Establish this repo as a stand-alone package for ST4

### PR DESCRIPTION
**Pull request by FichteFoll**
This MR contains changes to the README and deletes the YAML macros files because I find them cumbersome to work with and not worth it in the current state of the syntax. Furthermore, it gets rid of an external dependency.

Additional actions performed outside of this merge request:

- The repo has been mirrored from https://github.com/vuejs/vue-syntax-highlight but not as a fork because I intend the two to go into different directions. This repo will focus on providing good syntax highlighting support for Vue while the original one can continue to maintain the tmLanguage syntax for Linguist.
- The previous `st4` branch is now `main` (also the default branch).
- The old tmLanguage file will be installable for ST2 and 3 from prefixed tags, created from the new `st2` branch (old `master`).
- Corresponding tags will be created later.

### CODE REVIEW

**Comment by deathaxe** [comment]
Maybe we can re-use `lang=...` attribute specific contexts from https://github.com/corneliusio/svelte-sublime which recently removed yaml macros and introduced named contexts for each script language.

**Comment by FichteFoll** [comment]
That sounds like a good idea. Feel free to add this in a separate PR. I have created some issues for useful things to consider from both the original repo and on my own that we could tackle at a later point.

**Comment by deathaxe** [comment]
OK, will wait for this to be merged. 

LGTM. btw.

**Comment by FichteFoll** [comment]
Thanks for the review.

**Pull request merged**
